# ==========================
# Core Configuration
# ==========================
spring.application.name=notification-service
server.port=8086

# TẮT BANNER ASCII SPRING BOOT
spring.main.banner-mode=off

# ==========================
# Database & Datasource
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-notification:5432/notification_service_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres_password_123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=notification
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

# ==========================
# Logging Configuration
# ==========================
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=WARN
# Tắt bớt log Kafka
logging.level.org.apache.kafka=WARN
# ==========================
# Actuator / Security / Keys
# ==========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

jwt.secret=${JWT_SECRET:cruise-management-system-local-secret-key-2026}
internal.api-key=${INTERNAL_API_KEY:local-internal-api-key-change-me}

# ==========================
# Mail Configuration
# ==========================

notification.email.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhquanthcs257@gmail.com
spring.mail.password=ewqmrphkmazmfdqb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true