# /resource/application-pro.properties
# PostgreSQL Database Config (Production)
spring.datasource.url=jdbc:postgresql://postgres:5432/cruise_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (HikariCP) optimization for Prod
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# JPA & Hibernate Config for Production
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# An toàn cho Prod: chỉ kiểm tra schema chứ không tự tạo/xóa bảng
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Server Port
server.port=8081

# Logging level cho Prod (Chỉ logWARN/ERROR)
logging.level.root=WARN
logging.level.com.cruise=INFO
