FROM maven:3.9.11-eclipse-temurin-17

WORKDIR /app

# ==========================
# 1. Copy và build thư viện Common trước
# ==========================
COPY common/pom.xml ./common/pom.xml
COPY common/src ./common/src

# Cài đặt thư viện common vào local maven repository của container
RUN mvn -f common/pom.xml clean install -DskipTests

# ==========================
# 2. Copy và build Booking Service
# ==========================
COPY booking/pom.xml ./booking/pom.xml
COPY booking/src ./booking/src

WORKDIR /app/booking

# Tải dependency của booking-service
RUN mvn dependency:go-offline -B

# Chạy service
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false"]