FROM maven:3.9.11-eclipse-temurin-17

WORKDIR /app

# ==========================
# 1. Build & Install Module Common
# ==========================
COPY common/pom.xml ./common/pom.xml
COPY common/src ./common/src

RUN mvn -f common/pom.xml clean install -DskipTests

# ==========================
# 2. Prepare Activity Visit Service
# ==========================
COPY activity-visit-service/pom.xml ./activity-visit-service/pom.xml
COPY activity-visit-service/src ./activity-visit-service/src

WORKDIR /app/activity-visit-service

RUN mvn -B dependency:go-offline

CMD ["mvn", "spring-boot:run"]