# App Name
spring.application.name=cruise

# Profile mặc định
spring.profiles.active=dev

# Cấu hình Hibernate / JPA Base
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# TẮT LOG HIBERNATE
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

# Cấu hình Upload File & Tomcat Request Size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.max-http-header-size=10MB
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB

# Path matching strategy
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Cấu hình JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}